# -*- coding: utf-8 -*-
"""Mini_Task_Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wynxfYwx23DVI4N2js82CF-YVyc3lv3p

3. Streamlit App (app.py)
"""

!pip install streamlit

import streamlit as st
# from scraper import scrape_website # Removed this line

st.title("🌐 Web Scraper and Report Generator")
st.markdown("Enter a website URL and scrape all pages (including subpages) to generate a report.")

url = st.text_input("Enter website URL", "https://example.com")
depth = st.slider("Crawl Depth", 1, 3, 1)

if st.button("Scrape"):
    with st.spinner("Scraping website..."):
        report = scrape_website(url, depth=depth)
        # Save report
        with open("report.txt", "w", encoding="utf-8") as f:
            f.write(report)
        st.success("✅ Scraping completed!")
        st.download_button("📥 Download Report", report, file_name="report.txt")
        st.text_area("Report Preview", report[:2000])  # preview first part